version: '3.8'

services:
  # Local PostgreSQL instance for testing
  pgsqlserver:
    container_name: pgsqlserver-ctnr
    image: pgsqlserver-img
    build:
      context: ./database/
      dockerfile: ./docker/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./database/docker/.pgsql.env
    volumes:
      - type: volume
        source: pgsql_server_data
        target: /var/lib/postgresql/pgdata
    ports:
      - target: 5432
        published: 5432
    networks:
      - packiot-fsc-network

networks:
  packiot-fsc-network:

volumes:
  pgsql_server_data:
