name: PackIOT Full-Stack Challenge Pipelines

on:
  push:
    branches:
      - master
      - 'packiotfsc/**'
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        if [ -f requirements.txt ]; then pip install -r requirements.txt --no-cache-dir; fi
    - name: Lint Python with prospector
      run: |
        ./scripts/devenv.py code python lint
    - name: Lint SQL with SQLFluff
      run: |
        ./scripts/devenv.py code sql lint
